import { CampaignItem, CreativeItem, ProofOfPlayEvent } from './types';

export const INITIAL_CAMPAIGNS: CampaignItem[] = [
  {
    id: 'camp-1',
    name: 'Campaign Name 1',
    client: 'Apex Automotive Global',
    status: 'Active',
    schedule: '06:00 AM - 08:00 PM',
    deliveryPercent: 85,
    approved: true,
    type: 'Guaranteed',
    priority: 'Protected',
    impressionsDelivered: '2.4M',
    revenue: '$48,200',
  },
  {
    id: 'camp-2',
    name: 'Campaign Name 2',
    client: 'Global Airlines Flight 77',
    status: 'Active',
    schedule: '06:00 AM - 08:00 PM',
    deliveryPercent: 70,
    approved: true,
    type: 'Programmatic',
    priority: 'Prioritized',
    impressionsDelivered: '1.9M',
    revenue: '$32,500',
  },
  {
    id: 'camp-3',
    name: 'Campaign Name 3',
    client: 'Fresh Market Organic',
    status: 'Active',
    schedule: '06:00 AM - 08:00 PM',
    deliveryPercent: 95,
    approved: true,
    type: 'Guaranteed',
    priority: 'Protected',
    impressionsDelivered: '3.1M',
    revenue: '$64,000',
  },
  {
    id: 'camp-4',
    name: 'Campaign Name 4',
    client: 'GeoTech Solutions AI',
    status: 'Pending',
    schedule: '06:00 AM - 08:00 PM',
    deliveryPercent: 82,
    approved: true,
    type: 'Direct',
    priority: 'Normal',
    impressionsDelivered: '1.5M',
    revenue: '$28,400',
  },
  {
    id: 'camp-5',
    name: 'Campaign Name 5',
    client: 'Quantum Streaming Plus',
    status: 'Active',
    schedule: '06:00 AM - 08:00 PM',
    deliveryPercent: 91,
    approved: true,
    type: 'Guaranteed',
    priority: 'Protected',
    impressionsDelivered: '4.2M',
    revenue: '$85,000',
  },
  {
    id: 'camp-6',
    name: 'Campaign Name 6',
    client: 'Urban Fashion Apparel',
    status: 'Active',
    schedule: '06:00 AM - 08:00 PM',
    deliveryPercent: 72,
    approved: true,
    type: 'Programmatic',
    priority: 'Prioritized',
    impressionsDelivered: '890K',
    revenue: '$19,800',
  },
  {
    id: 'camp-7',
    name: 'Campaign Name 7',
    client: 'Metro Transit Cards',
    status: 'Pending',
    schedule: '06:00 AM - 08:00 PM',
    deliveryPercent: 75,
    approved: false,
    type: 'Direct',
    priority: 'Normal',
    impressionsDelivered: '1.1M',
    revenue: '$21,300',
  },
  {
    id: 'camp-8',
    name: 'Campaign Name 8',
    client: 'Solaris Energy Drink',
    status: 'Active',
    schedule: '06:00 AM - 08:00 PM',
    deliveryPercent: 80,
    approved: true,
    type: 'Guaranteed',
    priority: 'Protected',
    impressionsDelivered: '2.8M',
    revenue: '$55,000',
  },
];

export const INITIAL_CREATIVES: CreativeItem[] = [
  {
    id: 'cr-1',
    title: 'City Skyline & EV Ad',
    category: 'Automotive & Transit',
    status: 'Review',
    statusColor: 'amber',
    aspectRatio: '16:9 Landscape',
    resolution: '3840 x 2160 (4K UHD)',
    duration: '15 sec',
    imageUrl: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=600&q=80',
    notes: 'Awaiting contrast validation check for high-sun daylight playback.',
    advertiser: 'Apex Automotive',
  },
  {
    id: 'cr-2',
    title: 'Global Airlines Flight',
    category: 'Travel & Hospitality',
    status: 'Review',
    statusColor: 'amber',
    aspectRatio: '9:16 Portrait LED',
    resolution: '1080 x 1920 (FHD)',
    duration: '10 sec',
    imageUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=600&q=80',
    notes: 'Audio-less video track verified. Color profile sRGB standard.',
    advertiser: 'Global Airlines',
  },
  {
    id: 'cr-3',
    title: 'Times Square Neon Tech',
    category: 'Consumer Electronics',
    status: 'Approved',
    statusColor: 'green',
    aspectRatio: '1:1 Square Digital',
    resolution: '2048 x 2048',
    duration: '15 sec',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80',
    notes: 'Approved by OOH Compliance team for prime evening prime-time rotation.',
    advertiser: 'GeoTech Solutions',
  },
  {
    id: 'cr-4',
    title: 'Fresh Market Organic',
    category: 'Retail & Grocery',
    status: 'Ready',
    statusColor: 'cyan',
    aspectRatio: '16:9 Highway Banner',
    resolution: '1920 x 1080',
    duration: '15 sec',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=600&q=80',
    notes: 'Assets cached locally on edge hardware media players.',
    advertiser: 'Fresh Market',
  },
];

export const PROOF_OF_PLAY_DATA: ProofOfPlayEvent = {
  id: 'pop-1432',
  timestamp: '14:32:05',
  status: 'SUCCESSFUL',
  duration: '15s',
  billboardId: 'Billboard A-4',
  billboardName: 'Times Square Broadway Spectacular LED',
  campaign: 'Global Brand Launch Campaign',
  client: 'Premium Brand Advertiser',
  location: 'Times Square, NYC (Billboard A-4)',
  lat: 40.758,
  long: -73.9855,
  impressions: 18450,
  loopPosition: 4,
  quality: '4K UHD',
  imageUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=1000&q=85',
};
